### ISSUE TITLE
Frontend: No calendar picker when editing date cells

### ISSUE THREAD

**Issue by Ralle8m** [Theophilix/event-table-edit#152]
Try to edit on frontend an field type date format - it don't show the calendar icon to pick the date.

**Comment by Theophilix** [comment]
Thank you for reporting this problem. It will be fixed soon.
You could change the datatype to "text" meanwhile.

**Comment by Theophilix** [comment]
Fixed in 4.7.9 version

**Comment by Ralle8m** [comment]
Stil facing problems within this - the function is working - but the calendar icon is still missing. If i check the code the css shows me that the calendar icon is coming from ico-moon font (protostar template) - maybe you have to change the icon to a image like the ok- or cancel-button. You can test it yourself by choosing another template like helix-ultimate.

![Bildschirmfoto 2019-09-27 um 13 22 14](https://user-images.githubusercontent.com/55754694/65765955-d978eb80-e129-11e9-9ba2-9424b7074ee7.png)

**Comment by Theophilix** [comment]
Oh no...thanks for reporting this. In my demo (demo.eventtableedit.com) everything works
